collections:
  topics:
    output: true
  concepts:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  - scope:
      path: ""
      type: "concepts"
    values:
      layout: "concept"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

baseurl: /math
# url: "cosmo-memories.github.io"
# permalink: /:title 